### ISSUE TITLE
reQ

### ISSUE THREAD

**Issue by 0x3W** [jonathonmcmurray/ws.q#2]
Good evening,

library and examples look great, I tried running it though but reQ seems to be missing atm, any idea how it might be solved?

    'reQ/req.q. OS reports: No such file or directory

Kind regards,

**Comment by 0x3W** [comment]
I used req.q from the other depository, but still get weird result back, any idea how to get it going?

    ~/q/m32🍀 $ ./q examples/gdax.q -p 5001
    KDB+ 3.3 2015.06.09 Copyright (C) 1993-2015 Kx Systems
    m32/ 4()core 16384MB Dovla dovla.local 192.168.1.193 NONEXPIRE

    Fire in the hole!

    {[m;u;hd;p;v]

      pr:proxy h:host u;
      nu:$[@[value;`.doh.ENABLED;0b];.doh.resolve;]u;
      hs:hsurl `$prot[nu],host nu;
      if[pr[0];hs:hsurl `$prot[pr 1],host pr 1];
      us:user $[pr 0;pr 1;nu];
      if[count c:getcookies[prot nu;h;endp nu];hd[`Cookie]:c];
      d:headers[us;pr;hd;p];
      r:hs d:buildquery[m;pr;nu;h;d;p];
      if[v;-1"-- REQUEST --\n",string[hs],"\n",d];
      if[v;-1"-- RESPONSE --\n",r];
      r:formatresp r;
      if[(sc:`$"Set-Cookie") in k:key r 0;
         addcookie[h]'[value[r 0]where k=sc]];
      if[r[0][`status] within 300 399;
         lo:$["/"=r[0][`Location]0;prot[u],user[u],host[u],r[0]`Location;r[0]`Location];
         :.z.s[m;lo;hd;p;v]];
      :r;
     }
    'type
     @
     `:https://api.gdax.com
      "GET /products HTTP/1.1\r\nHost: api.gdax.com\r\nConnection: Close\r\nUser-Ag..

    q.req))\a
    ,`cookiejar

    q.req))cookiejar
    (+`host`path`name!(();();()))!+`val`expires`maxage`secure`httponly`samesite!(..
    q.req))

**Comment by jonathonmcmurray** [comment]
Hi @0x3W 

reQ is a "submodule" of this git repo, which means when cloning the repo you need to use the `--recursive` flag i.e.

```
git clone --recursive https://github.com/jonathonmcmurray/ws.q.git
```

However, I'm not completely sure of the issue with downloading the GDAX product list here, with `reQ/req.q` available I'm unclear what could be the problem here. Do you have SSL certificates set up? e.g. if you try using .Q.hg to query the URL, what happens?

```
q).Q.hg`:https://api.gdax.com/products
"{\"message\":\"User-Agent header is required.\"}"
```

(note that `.Q.hg` is missing `User-Agent` header on request, hence the requirement to use reQ)

Also apologies for delay in responding to this

**Comment by 0x3W** [comment]
Good evening,

I apologize for a newbie mistake with recursive downloading, I managed to get it to work.

When I run 

      q).Q.hg`:https://api.gdax.com/products

First I get error with certificates, how to resolve it?

    2847064560:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:255:fopen('/private/etc/ssl/server-crt.pem', 'r')
    2847064560:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:257:
    2847064560:error:140AD002:SSL routines:SSL_CTX_use_certificate_file:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/ssl/ssl_rsa.c:437:
    2847064560:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:122:fopen('/private/etc/ssl/cacert.pem', 'r')
    2847064560:error:2006D080:BIO routines:BIO_new_file:no such file:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/bio/bss_file.c:125:
    2847064560:error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/x509/by_file.c:252:
    'conn. OS reports: Protocol not available
     [0]  .Q.hg`:https://api.gdax.com/products
       ^

then I repeat command and it works

     q)).Q.hg`:https://api.gdax.com/products
     "{\"message\":\"User-Agent header is required.\"}"

**Comment by jonathonmcmurray** [comment]
So this is an issue of missing SSL certificates required to verify a download from an HTTPS URL; there are a couple of ways to set this up. You can see one option here: https://code.kx.com/q/cookbook/ssl/#tls-client-mode

Essentially this:

```
$ curl https://curl.haxx.se/ca/cacert.pem > $HOME/certs/cabundle.pem
$ export SSL_CA_CERT_FILE=$HOME/certs/cabundle.pem
```

(you can save to whatever location you would prefer)

Alternatively, if you happen to have [Anaconda](https://www.anaconda.com/) set up, you can install my `qhttps` package which will set up kdb+ to use certificates installed via Anaconda. To do this, simply run this command at your prompt (you'll need to have your Anaconda environment activated when running q):

```
$ conda install -c jmcmurray qhttps
```

(I'll soon be adding a package for this repo to Anaconda, easing the installation process; it'll be a similar command to the above which will automatically set up the reQ library, HTTPS certs etc.)

**Comment by 0x3W** [comment]
Thank You so much for detailed explanation. Amazing library!

**Comment by jonathonmcmurray** [comment]
@0x3W I'm going to close this issue as I think it's resolved, if you have any  further issues feel free to open another
