### ISSUE TITLE
websocket connection to Solace

### ISSUE THREAD

**Issue by himoacs** [jonathonmcmurray/ws.q#5]
Hi,

I am trying to open a websocket connection to Solace messaging service. Solace has a host/port that I am supposed to connect to but when I use your examples, it doesn't seem to be working. 

Here is what I am doing:

q).echo.upd:show;.echo.h:.ws.open["wss://vmr-mr8v6yiwiawh.messaging.solace.cloud:20292";`.echo.upd]
-- REQUEST --
:wss://vmr-mr8v6yiwiawh.messaging.solace.cloud:20292 GET / HTTP/1.1
Host: vmr-mr8v6yiwiawh.messaging.solace.cloud:20292
Origin: vmr-mr8v6yiwiawh.messaging.solace.cloud:20292

-- RESPONSE --
HTTP/1.1 400 Internal resource not available: UNKNOWN parser create failed
Server: SolTR/8.11.0.1033
Content-Length: 0
Cache-Control: no-cache

Do you know what I am doing wrong?

If you are interested, you can setup a Solace account here (https://console.solace.cloud) and test with your own instance.

Thanks in advance,
Himanshu

**Comment by jonathonmcmurray** [comment]
I'll take a look and get back to you!

**Comment by himoacs** [comment]
Thanks, I would really appreciate that!

**Comment by jonathonmcmurray** [comment]
Apologies for the (very) delayed response. I took a look, and it seems that Solace is using WebSockets as a transport mechanism, but appear to have their own protocol on top of this (they have a client library for JS etc.). I don't think it would be trivial to implement this in q

**Comment by jonathonmcmurray** [comment]
Closing as there doesn't seem to be a simple way to support Solace websockets
