### ISSUE TITLE
Websocket dropping off after working for a little while

### ISSUE THREAD

**Issue by ksk438** [jonathonmcmurray/ws.q#7]
I am using the gdax.q example provided....it works for a little while and then dies out -> with .z.W going empty and .z.wc being called. I tried modifying the file to reconnect (using .z.wc) when the connection closes:

```
connect:{
        .gdax.h:.ws.open["wss://ws-feed.gdax.com";`.gdax.upd];                               //open websocket to feed
        .gdax.sub[.gdax.h;`$"ETH-USD";`trade];                                                   //subscribe to L2 & trade data for ETH-USD
        .gdax.sub[.gdax.h;`$"BTC-USD";`trade];                                                   //subscribe to L2 & trade data for BTC-GBP
        0N!"re-connected"
        }

.gdax.ref:.gdax.getref[];
connect[];
.z.wc:{connect[]};

\t 1000
```

It reconnects a few times before dying with the following message - and my entire q processes is killed:

```
'2018.12.13T21:00:08.341 couldn't report -- exiting
```

**Comment by jonathonmcmurray** [comment]
I'll take a look into this, but at first glance, I think you are using kdb+ on demand, which reports to kx periodically while running - it looks like it was unable to report to kx, at which point the session gets killed.

Is it possible there are intermittent network issues on your system?

**Comment by ksk438** [comment]
This seems unlikely because I would expect every q process to die in the same manner if that was the case

Does the websocket die for you or anyone else? 

```
q)count trade
7
q)0D15:40:45.266679000
4i
"re-connected"
0D15:41:15.266266000
4i
"re-connected"
count trade
106
q)0D15:42:46.480507000
4i
"re-connected"
0D15:43:15.556585000
4i
"re-connected"
count trade
206
q)'2018.12.14T15:44:44.743 couldn't report -- exiting
```

It also seems like less trades than expected...would you agree?

**Comment by jonathonmcmurray** [comment]
Apologies it took me a while to follow up on this.

Using 64bit kdb+ On Demand, I see the same as you (tried with both 3.5 & 3.6). After talking to kx, I downloaded a newer build (by re-applying at https://ondemand.kx.com/ & using download link in new email). With updated build (`.z.k=2018.12.06`), I do not see disconnections. Please update your kdb+ build & try again.

Note that newest build on Anaconda is `.z.k=2018.10.23`, which does not appear to have fixed this issue. So if you install kdb via conda, you will need to manually update or wait for a newer build to reach Anaconda I think.

Also, running the same code with 32bit Personal Edition, it works as I expect.

---

Regarding the lower numbers than you expect; there is a sequence number included in the `trade` table (`tid`) which should be sequential for a given ticker. You should be able to query with something like the following to find if there are missing trades:

```q
q)select from trade where 1<(deltas;tid) fby sym
time                          sym    price   bid     ask     side tid      si..
-----------------------------------------------------------------------------..
2018.12.17D16:43:08.517000000 BTCUSD 3415.57 3415.57 3415.73 sell 56073840 0...
2018.12.17D16:43:23.578000000 BTCUSD 3416.55 3415.32 3417    buy  56073856 0...
2018.12.17D16:43:23.578000000 BTCUSD 3417.5  3417.49 3417.5  buy  56073864 0...
```

The GDAX example is something I wrote in a couple of hours, it's not really a "complete" implementation. Looking now at the GDAX (now Coinbase Pro) API docs, there is mention of how messages can be dropped. https://docs.pro.coinbase.com/#sequence-numbers

https://docs.pro.coinbase.com/#the-matches-channel mentions as well that when sequence number increases by more than 1, we should use REST API to download messages that are dropped; this is something I didn't implement in the GDAX example, but most likely this is something that would need implemented for using this code fully. I'll look at implementing that change

**Comment by jonathonmcmurray** [comment]
@ksk438 I assume the disconnection bug is fixed by updating kdb+, closing issue

**Comment by secwang** [comment]
this issue help me a lot.

conda version kx 4.0 l64 have this issue
