### ISSUE TITLE
.req.host   no function in req.q

### ISSUE THREAD

**Issue by tfangz888** [jonathonmcmurray/ws.q#8]
q).echo.h:.ws.open["ws://demos.kaazing.com/echo";`.echo.upd]
'.req.host
  [2]  /home/toby/miniconda3/envs/kdb/q/packages/ws-client/ws.q:10: .ws.open0:{[x;y;v]
  pr:.req.proxy h:.req.host x;                                          //handle proxy if needed,get host
                  ^
  hs:.req.hsurl[.req.prot[x],h];                                        //get hsym of host
q.ws))

**Comment by jonathonmcmurray** [comment]
Thanks, I think some updates might be necessary due to some changes in reQ. Just to confirm, how did you install & load the libraries? (i.e. was it via anaconda & qutil, or manually?)

**Comment by jonathonmcmurray** [comment]
Put the wrong issue number in the commit, but this commit should fix the issue: https://github.com/jonathonmcmurray/ws.q/commit/e324fc5b766c1c76afb448648f4420c8a2698337

I've also uploaded an updated build to Anaconda, so installation via conda should be working OK now as well.

To alleviate these dependency issues, I am considering folding the `ws-client` functionality into the `reQ` library - at present it's a pretty small addition on top of `reQ` anyway. Then this repo would only be for the `ws-server` functionality.

Out of curiosity - do you have a use case in mind for the library, and if so do you see any issues with the functionality moving into reQ library?
